services:
  relational-db:
    image: sqlserver_sureprofit
    container_name: sqlserver_sureprofit
    build:
      context: ./
      dockerfile: ./docker/sqlserver/Dockerfile
    ports:
      - 1433:1433
    volumes:
      - ./docker/sqlserver/data:/var/opt/mssql/data